### ISSUE TITLE
PubSubHubbub Core 0.4: Validation vs. verification of intent

### ISSUE THREAD

**Issue by cweiske** [pubsubhubbub/PubSubHubbub#25]
I found it hard to wrap my head around that there is a difference
between "validation" and "verification of intent", since I thought that
verifying the intent by calling the callback is a kind of validation
already.

Maybe it would help if an example for a validation rule/process would be
added to the spec.

**Comment by julien51** [comment]
Validation and verification of intent have different purposes and are intended to different entities.
- Validation is to make sure that the **publishers** allows for a given subscription. 
- Verification of intent is a dial-back mechanism to ensure that the origin of the subscription request is indeed the same entity which will get the notifications.

An example could help indeed, but I'm not sure the spec is the best place for it since validation is optional. (I want to make sure that examples are not interpreted as reference implementations).
