### ISSUE TITLE
PubSubHubbub Core 0.4: Fat pings vs. normal pings

### ISSUE THREAD

**Issue by cweiske** [pubsubhubbub/PubSubHubbub#26]
It currently only seems to be possible that the hub sends an update
notification to the subscriber that contains the (full) content of the
subscribed resource/topic (fat ping).

Sending only the POST request without any content (light ping) seems to
be a violation of the spec.

Is this intentional?
Shouldn't hubs be able to send light pings?

**Comment by julien51** [comment]
No. Hubs should _only_ send fat pings to avoid the thundering herd problem.

**Comment by aaronpk** [comment]
In reading the spec, it was not at all clear that it is required that hubs send the full (or diff'd) content.

> Notification: A payload describing how a topic's contents have changed, or the full updated content.

Since "a payload" is not really defined, I interpreted that to mean the payload could be the full HTML, a diff, a text description, or blank.

**Comment by julien51** [comment]
Well, it's not defined, because it depends on what the resource is... your forgot half the paragraph:

> A payload describing how a topic's contents have changed, or the full updated content. Depending on the topic's content type, the difference (or "delta") may be computed by the hub and sent to all subscribers.

For resources (like RSS/Atom) feeds where there is a clear diffing mechanism, then, the payload is the diff. For HTML, it's not as obvious.. for example.

But, yes, [fat pings are a requirement](http://techcrunch.com/2009/09/09/rsscloud-vs-pubsubhubbub-why-the-fat-pings-win/).
