### ISSUE TITLE
PubSubHubbub Core 0.4: Verification of intent vs. "denied"

### ISSUE THREAD

**Issue by cweiske** [pubsubhubbub/PubSubHubbub#27]
If the "verification of intent" fails, has the hub to inform the
subscriber (hub.mode=denied)?

Or more broadly, does a failed verification count as "denied"?

**Comment by julien51** [comment]
No... it's unnecessary because the subscriber knows about the outcome of the verification of intent. The subscriber is the entity which determines the outcome. 
In other words, if the subscribers _accepts_ the verification of intent, the subscription will be considered as done. If the subscriber _refuses_ the verification of intent, the subscription will be dropped.
