### ISSUE TITLE
PubSubHubbub Core 0.4: Verifying during subscription request

### ISSUE THREAD

**Issue by cweiske** [pubsubhubbub/PubSubHubbub#28]
Is it allowed to do the validation and verification of intent
process while the subscription request is running?

This would imply that the verification of intent callback and the
denied-callback is called when while the subscription request is still
being answered.

That would make it possible to skip all the worker setup that's
necessary to do delayed validation and verification.

Process diagram for inline validation:

```
client                     server/hub
 +---[subscription request]-->-----+
 |                                 |
 |  +<--[verification of intent]---+
 |  |
 |  +--[verification response]-->--+
 |                                 |
 |  +<--[denied callback]----------+
 |  |
 |  +----[response]------------->--+
 |                                 |
 +--<--[subscription response]-----+
```

This would also make it possible to not call the callback at all but
tell the denied-state directly in the response of the subscription
request. But that does not seem to be planned at all, right?

**Comment by julien51** [comment]
> Is it allowed to do the validation and verification of intent
> process while the subscription request is running?

No. We decided to remove the complexity of having 2 modes (async or sync -which you're describing). Sync was also creating issues in the context of application unable to handle more than one concurrent requests (GAE, Rails dev, Heroku applications... etc).

Also, the validation is inherently async because the publisher can take _days_ before confirming that  subscription is allowed...
