### ISSUE TITLE
Empty Notification Body Received After Successful PubSubHubbub Subscription Verification

### ISSUE THREAD

**Issue by zelalem61** [pubsubhubbub/PubSubHubbub#73]
I subscribed to PubSubHubbub using the URL https://pubsubhubbub.appspot.com/subscribe, and my subscription was successfully verified. However, when I upload a new video to my channel, I receive a notification at my callback URL, but the body of the notification is empty.
![ver](https://github.com/user-attachments/assets/1bdf083d-4d45-412c-8079-a718d7e1ad6f)

**Comment by maksverver** [comment]
Hi Zelalem,

This repository contains the PubSubHubbub protocol specification. It is not a general forum for discussing individual hubs or debugging issues with subscriptions to particular feeds. That's why I'll close the issue.

If you need help figuring out what goes wrong, I suggest that you ask a question on a forum like Stack Overflow which is intended for that purpose.
