### ISSUE TITLE
Allow "sync" verification

### ISSUE THREAD

**Issue by evanp** [pubsubhubbub/PubSubHubbub#9]
PuSH 0.3 allowed a "sync" verification mechanism.

It's not clear to me why we pulled this out.

**Comment by jobetudiant** [comment]
Because it can't work if we want the feed publisher's approval. 
If you're a subscriber and want 'sync', but the feed is protected, you won't get an verification right away, as the hub needs to ask the publisher. 

In my experience, having 2 different modes made things a lot messier for a lot of people.
I'm in favor of using the mode that allows everyone to get stuff done, rather than 2 modes where people pick the wrong one and eventually figure out that the one they picked didn't work.

**Comment by superfeedr** [comment]
Dammit! Wrong Github account... but the previous comment was from me!

**Comment by evanp** [comment]
Seems like a negotiation process at subscription time, then.

```
if (topic requires async) {
    if (subscriber only does sync) {
        hub returns 400 failure;
    } else {
        do async;
  }
} else {
    if (subscriber only does sync) {
        do sync;
    } else if (subscriber only does async) {
        do async;
    } else {
        do either!;
    }
}
```

**Comment by superfeedr** [comment]
Complexity... and weirdness. Why would we let subscribers assume they can do "sync" when they can't?

**Comment by superfeedr** [comment]
Another problem with the sycn approach is that it the subscriber cannot know before actually subscribing whether the feed requires a publisher validation... and if it does, then, there is no way this can be sync'ed, because the publisher may take time (at least user authorization) before it validates the subscription...
